- name: Creating Internet Gateway
  ec2_vpc_igw:
          aws_access_key: "{{ aws_id }}"
          aws_secret_key: "{{ aws_key }}"
          region: "{{ aws_region }}"
          vpc_id: "{{ ansibleVPC.vpc.id }}"
          state: present
  register: ansibleIGW

- name: Interet Gateway
  debug:
     var: ansibleIGW
