- name: Security Group Creation
  ec2_group:
          name: ansible_grp
          description: ansible group 
          vpc_id: "{{ ansibleVPC.vpc.id }}"
          region: "{{ aws_region }}"
          aws_secret_key: "{{ aws_key }}"
          aws_access_key: "{{ aws_id }}"
          rules:
                  - proto: tcp
                    ports: 22
                    cidr_ip: 0.0.0.0/0
  register: ansibleSG

- name : Displaying Security Group Info
  debug:
          var: ansibleSG

